<?php

/**
 * BaseSede_Cliente
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idCustomer
 * @property string $identification
 * @property string $idCustomerOffice
 * @property string $address
 * @property string $name
 * @property integer $countryId
 * @property string $countryName
 * @property integer $cityId
 * @property string $cityName
 * @property string $contactPerson1
 * @property string $cellphoneContact
 * @property string $phoneNumber
 * @property Cliente $Cliente
 * 
 * @method integer      getIdCustomer()       Returns the current record's "idCustomer" value
 * @method string       getIdentification()   Returns the current record's "identification" value
 * @method string       getIdCustomerOffice() Returns the current record's "idCustomerOffice" value
 * @method string       getAddress()          Returns the current record's "address" value
 * @method string       getName()             Returns the current record's "name" value
 * @method integer      getCountryId()        Returns the current record's "countryId" value
 * @method string       getCountryName()      Returns the current record's "countryName" value
 * @method integer      getCityId()           Returns the current record's "cityId" value
 * @method string       getCityName()         Returns the current record's "cityName" value
 * @method string       getContactPerson1()   Returns the current record's "contactPerson1" value
 * @method string       getCellphoneContact() Returns the current record's "cellphoneContact" value
 * @method string       getPhoneNumber()      Returns the current record's "phoneNumber" value
 * @method Cliente      getCliente()          Returns the current record's "Cliente" value
 * @method Sede_Cliente setIdCustomer()       Sets the current record's "idCustomer" value
 * @method Sede_Cliente setIdentification()   Sets the current record's "identification" value
 * @method Sede_Cliente setIdCustomerOffice() Sets the current record's "idCustomerOffice" value
 * @method Sede_Cliente setAddress()          Sets the current record's "address" value
 * @method Sede_Cliente setName()             Sets the current record's "name" value
 * @method Sede_Cliente setCountryId()        Sets the current record's "countryId" value
 * @method Sede_Cliente setCountryName()      Sets the current record's "countryName" value
 * @method Sede_Cliente setCityId()           Sets the current record's "cityId" value
 * @method Sede_Cliente setCityName()         Sets the current record's "cityName" value
 * @method Sede_Cliente setContactPerson1()   Sets the current record's "contactPerson1" value
 * @method Sede_Cliente setCellphoneContact() Sets the current record's "cellphoneContact" value
 * @method Sede_Cliente setPhoneNumber()      Sets the current record's "phoneNumber" value
 * @method Sede_Cliente setCliente()          Sets the current record's "Cliente" value
 * 
 * @package    lalider
 * @subpackage model
 * @author     Miguel Marquez
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSede_Cliente extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('Sede_Cliente');
        $this->hasColumn('idCustomer', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('identification', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('idCustomerOffice', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('address', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('name', 'string', 200, array(
             'type' => 'string',
             'length' => 200,
             ));
        $this->hasColumn('countryId', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('countryName', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('cityId', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('cityName', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('contactPerson1', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('cellphoneContact', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('phoneNumber', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Cliente', array(
             'local' => 'idCustomer',
             'foreign' => 'idCustomer'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             'created' => 
             array(
              'name' => 'created_at',
              'type' => 'timestamp',
              'format' => 'Y-m-d H:i:s',
              'options' => 
              array(
              'notnull' => false,
              'required' => false,
              ),
             ),
             'updated' => 
             array(
              'name' => 'updated_at',
              'type' => 'timestamp',
              'format' => 'Y-m-d H:i:s',
              'options' => 
              array(
              'notnull' => false,
              'required' => false,
              ),
             ),
             ));
        $this->actAs($timestampable0);
    }
}