<?php

/**
 * CarteraTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CarteraTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CarteraTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Cartera');
    }
}