<?php

/**
 * Sede_ClienteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Sede_ClienteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Sede_ClienteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Sede_Cliente');
    }
}