<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2018/04/11 08:26:02

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=sf_lalider',
  'username' => 'root',
  'password' => '1234',
  'name' => 'doctrine',
)),);
